---
- name: configure virtual hosts
  template: >
    src="{{ item }}.j2"
    dest="/etc/nginx/sites-enabled/{{ item }}"
  with_items: "{{ nginx_sites }}"
  become: yes
  tags:
    - nginx
    - virtual-hosts
